{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyO5XM29KM/u4VOwChpeJBnU"
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "code",
      "source": [
        "import requests\n",
        "import folium\n",
        "import time\n",
        "from IPython.display import display, clear_output\n",
        "\n",
        "# URL API ISS\n",
        "URL = \"http://api.open-notify.org/iss-now.json\"\n",
        "\n",
        "# Lista per salvare il percorso\n",
        "percorso = []\n",
        "\n",
        "# Numero aggiornamenti (puoi aumentarlo)\n",
        "UPDATE_COUNT = 2000000\n",
        "\n",
        "# Intervallo aggiornamento (secondi)\n",
        "INTERVAL = 30\n",
        "\n",
        "\n",
        "def get_iss_position():\n",
        "    response = requests.get(URL)\n",
        "    data = response.json()\n",
        "\n",
        "    lat = float(data['iss_position']['latitude'])\n",
        "    lon = float(data['iss_position']['longitude'])\n",
        "\n",
        "    return lat, lon\n",
        "\n",
        "\n",
        "def is_over_italy(lat, lon):\n",
        "    # Bounding box Italia (approssimato)\n",
        "    return 36 < lat < 47 and 6 < lon < 19\n",
        "\n",
        "\n",
        "def create_map(percorso, lat, lon):\n",
        "    mappa = folium.Map(\n",
        "        location=[lat, lon],\n",
        "        zoom_start=3,\n",
        "        tiles=\"OpenStreetMap\"\n",
        "    )\n",
        "\n",
        "    # Marker ISS\n",
        "    folium.Marker(\n",
        "        [lat, lon],\n",
        "        tooltip=\"ISS - posizione attuale\",\n",
        "        icon=folium.Icon(color=\"red\", icon=\"info-sign\")\n",
        "    ).add_to(mappa)\n",
        "\n",
        "    # Percorso tracciato\n",
        "    if len(percorso) > 1:\n",
        "        folium.PolyLine(\n",
        "            percorso,\n",
        "            color=\"red\",\n",
        "            weight=2\n",
        "        ).add_to(mappa)\n",
        "\n",
        "    return mappa\n",
        "\n",
        "\n",
        "def main():\n",
        "    print(\"🚀 Avvio ISS Tracker...\\n\")\n",
        "\n",
        "    for i in range(UPDATE_COUNT):\n",
        "        lat, lon = get_iss_position()\n",
        "\n",
        "        percorso.append([lat, lon])\n",
        "\n",
        "        # Pulizia output per effetto live\n",
        "        clear_output(wait=True)\n",
        "\n",
        "        print(f\"🛰️ Aggiornamento #{i+1}\")\n",
        "        print(f\"Latitudine: {lat}\")\n",
        "        print(f\"Longitudine: {lon}\")\n",
        "\n",
        "        # Controllo Italia\n",
        "        if is_over_italy(lat, lon):\n",
        "            print(\"🇮🇹 ISS sopra l'Italia!\")\n",
        "\n",
        "        # Creazione mappa\n",
        "        mappa = create_map(percorso, lat, lon)\n",
        "\n",
        "        display(mappa)\n",
        "\n",
        "        # Attesa\n",
        "        time.sleep(INTERVAL)\n",
        "\n",
        "\n",
        "if __name__ == \"__main__\":\n",
        "    main()"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 693
        },
        "id": "ZxalN3u45Itb",
        "outputId": "f88a3b3b-ae54-4650-e896-e0290bad53f9"
      },
      "execution_count": null,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "🛰️ Aggiornamento #19\n",
            "Latitudine: -38.8741\n",
            "Longitudine: 166.3499\n"
          ]
        },
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "<folium.folium.Map at 0x7f83ed21ae40>"
            ],
            "text/html": [
              "<div style=\"width:100%;\"><div style=\"position:relative;width:100%;height:0;padding-bottom:60%;\"><span style=\"color:#565656\">Make this Notebook Trusted to load map: File -> Trust Notebook</span><iframe srcdoc=\"&lt;!DOCTYPE html&gt;\n",
              "&lt;html&gt;\n",
              "&lt;head&gt;\n",
              "    \n",
              "    &lt;meta http-equiv=&quot;content-type&quot; content=&quot;text/html; charset=UTF-8&quot; /&gt;\n",
              "    &lt;script src=&quot;https://cdn.jsdelivr.net/npm/leaflet@1.9.3/dist/leaflet.js&quot;&gt;&lt;/script&gt;\n",
              "    &lt;script src=&quot;https://code.jquery.com/jquery-3.7.1.min.js&quot;&gt;&lt;/script&gt;\n",
              "    &lt;script src=&quot;https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js&quot;&gt;&lt;/script&gt;\n",
              "    &lt;script src=&quot;https://cdnjs.cloudflare.com/ajax/libs/Leaflet.awesome-markers/2.0.2/leaflet.awesome-markers.js&quot;&gt;&lt;/script&gt;\n",
              "    &lt;link rel=&quot;stylesheet&quot; href=&quot;https://cdn.jsdelivr.net/npm/leaflet@1.9.3/dist/leaflet.css&quot;/&gt;\n",
              "    &lt;link rel=&quot;stylesheet&quot; href=&quot;https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css&quot;/&gt;\n",
              "    &lt;link rel=&quot;stylesheet&quot; href=&quot;https://netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css&quot;/&gt;\n",
              "    &lt;link rel=&quot;stylesheet&quot; href=&quot;https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@6.2.0/css/all.min.css&quot;/&gt;\n",
              "    &lt;link rel=&quot;stylesheet&quot; href=&quot;https://cdnjs.cloudflare.com/ajax/libs/Leaflet.awesome-markers/2.0.2/leaflet.awesome-markers.css&quot;/&gt;\n",
              "    &lt;link rel=&quot;stylesheet&quot; href=&quot;https://cdn.jsdelivr.net/gh/python-visualization/folium/folium/templates/leaflet.awesome.rotate.min.css&quot;/&gt;\n",
              "    \n",
              "            &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width,\n",
              "                initial-scale=1.0, maximum-scale=1.0, user-scalable=no&quot; /&gt;\n",
              "            &lt;style&gt;\n",
              "                #map_8b15d6a7fe80015aa3790c1c1f6c196d {\n",
              "                    position: relative;\n",
              "                    width: 100.0%;\n",
              "                    height: 100.0%;\n",
              "                    left: 0.0%;\n",
              "                    top: 0.0%;\n",
              "                }\n",
              "                .leaflet-container { font-size: 1rem; }\n",
              "            &lt;/style&gt;\n",
              "\n",
              "            &lt;style&gt;html, body {\n",
              "                width: 100%;\n",
              "                height: 100%;\n",
              "                margin: 0;\n",
              "                padding: 0;\n",
              "            }\n",
              "            &lt;/style&gt;\n",
              "\n",
              "            &lt;style&gt;#map {\n",
              "                position:absolute;\n",
              "                top:0;\n",
              "                bottom:0;\n",
              "                right:0;\n",
              "                left:0;\n",
              "                }\n",
              "            &lt;/style&gt;\n",
              "\n",
              "            &lt;script&gt;\n",
              "                L_NO_TOUCH = false;\n",
              "                L_DISABLE_3D = false;\n",
              "            &lt;/script&gt;\n",
              "\n",
              "        \n",
              "&lt;/head&gt;\n",
              "&lt;body&gt;\n",
              "    \n",
              "    \n",
              "            &lt;div class=&quot;folium-map&quot; id=&quot;map_8b15d6a7fe80015aa3790c1c1f6c196d&quot; &gt;&lt;/div&gt;\n",
              "        \n",
              "&lt;/body&gt;\n",
              "&lt;script&gt;\n",
              "    \n",
              "    \n",
              "            var map_8b15d6a7fe80015aa3790c1c1f6c196d = L.map(\n",
              "                &quot;map_8b15d6a7fe80015aa3790c1c1f6c196d&quot;,\n",
              "                {\n",
              "                    center: [-38.8741, 166.3499],\n",
              "                    crs: L.CRS.EPSG3857,\n",
              "                    ...{\n",
              "  &quot;zoom&quot;: 3,\n",
              "  &quot;zoomControl&quot;: true,\n",
              "  &quot;preferCanvas&quot;: false,\n",
              "}\n",
              "\n",
              "                }\n",
              "            );\n",
              "\n",
              "            \n",
              "\n",
              "        \n",
              "    \n",
              "            var tile_layer_1514d735b9562f068c2bab67f52c2bf9 = L.tileLayer(\n",
              "                &quot;https://tile.openstreetmap.org/{z}/{x}/{y}.png&quot;,\n",
              "                {\n",
              "  &quot;minZoom&quot;: 0,\n",
              "  &quot;maxZoom&quot;: 19,\n",
              "  &quot;maxNativeZoom&quot;: 19,\n",
              "  &quot;noWrap&quot;: false,\n",
              "  &quot;attribution&quot;: &quot;\\u0026copy; \\u003ca href=\\&quot;https://www.openstreetmap.org/copyright\\&quot;\\u003eOpenStreetMap\\u003c/a\\u003e contributors&quot;,\n",
              "  &quot;subdomains&quot;: &quot;abc&quot;,\n",
              "  &quot;detectRetina&quot;: false,\n",
              "  &quot;tms&quot;: false,\n",
              "  &quot;opacity&quot;: 1,\n",
              "}\n",
              "\n",
              "            );\n",
              "        \n",
              "    \n",
              "            tile_layer_1514d735b9562f068c2bab67f52c2bf9.addTo(map_8b15d6a7fe80015aa3790c1c1f6c196d);\n",
              "        \n",
              "    \n",
              "            var marker_9e18d33d3480e31ac8a68f568effaf38 = L.marker(\n",
              "                [-38.8741, 166.3499],\n",
              "                {\n",
              "}\n",
              "            ).addTo(map_8b15d6a7fe80015aa3790c1c1f6c196d);\n",
              "        \n",
              "    \n",
              "            var icon_cfbb2fd7be91f5b24c2bfa87b6f39f6e = L.AwesomeMarkers.icon(\n",
              "                {\n",
              "  &quot;markerColor&quot;: &quot;red&quot;,\n",
              "  &quot;iconColor&quot;: &quot;white&quot;,\n",
              "  &quot;icon&quot;: &quot;info-sign&quot;,\n",
              "  &quot;prefix&quot;: &quot;glyphicon&quot;,\n",
              "  &quot;extraClasses&quot;: &quot;fa-rotate-0&quot;,\n",
              "}\n",
              "            );\n",
              "        \n",
              "    \n",
              "            marker_9e18d33d3480e31ac8a68f568effaf38.bindTooltip(\n",
              "                `&lt;div&gt;\n",
              "                     ISS - posizione attuale\n",
              "                 &lt;/div&gt;`,\n",
              "                {\n",
              "  &quot;sticky&quot;: true,\n",
              "}\n",
              "            );\n",
              "        \n",
              "    \n",
              "                marker_9e18d33d3480e31ac8a68f568effaf38.setIcon(icon_cfbb2fd7be91f5b24c2bfa87b6f39f6e);\n",
              "            \n",
              "    \n",
              "            var poly_line_15a5b2b60b975b2f91eddf7343a3d2ee = L.polyline(\n",
              "                [[-10.0588, 137.3825], [-11.5638, 138.5054], [-13.3374, 139.8516], [-15.7952, 141.7661], [-17.2747, 142.9511], [-18.7699, 144.1776], [-21.1748, 146.2204], [-23.1672, 147.9893], [-24.5923, 149.3041], [-26.5168, 151.1546], [-27.9753, 152.6223], [-29.392, 154.1092], [-30.7437, 155.5911], [-32.0969, 157.1442], [-33.8818, 159.3145], [-35.221, 161.0473], [-36.4695, 162.7559], [-37.6875, 164.5218], [-38.8741, 166.3499]],\n",
              "                {&quot;bubblingMouseEvents&quot;: true, &quot;color&quot;: &quot;red&quot;, &quot;dashArray&quot;: null, &quot;dashOffset&quot;: null, &quot;fill&quot;: false, &quot;fillColor&quot;: &quot;red&quot;, &quot;fillOpacity&quot;: 0.2, &quot;fillRule&quot;: &quot;evenodd&quot;, &quot;lineCap&quot;: &quot;round&quot;, &quot;lineJoin&quot;: &quot;round&quot;, &quot;noClip&quot;: false, &quot;opacity&quot;: 1.0, &quot;smoothFactor&quot;: 1.0, &quot;stroke&quot;: true, &quot;weight&quot;: 2}\n",
              "            ).addTo(map_8b15d6a7fe80015aa3790c1c1f6c196d);\n",
              "        \n",
              "&lt;/script&gt;\n",
              "&lt;/html&gt;\" style=\"position:absolute;width:100%;height:100%;left:0;top:0;border:none !important;\" allowfullscreen webkitallowfullscreen mozallowfullscreen></iframe></div></div>"
            ]
          },
          "metadata": {}
        }
      ]
    }
  ]
}